function init(self)
    msg.post(".", "acquire_input_focus")
    self.on_ground = false
end

function update(self, dt)
end

function on_message(self, message_id, message, sender)
    if message_id == hash("collision_point") then
        if message.normal.y > 0 then
            self.on_ground = true
        end
    elseif message_id == hash("collision_lost") then
        self.on_ground = false
    end
end

function on_input(self, action_id, action)
    if action_id == hash("jump") and action.pressed then
        if self.on_ground then
            physics.apply_impulse_at_position(go.get_position(), vec3(0, 500, 0))
            self.on_ground = false
        end
    end
end
